# Generated by Django 3.2.3 on 2021-05-30 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='phone',
            field=models.CharField(default=None, max_length=18, validators=[django.core.validators.RegexValidator(message='Insert a valid phone number. Examples: (99)99999-9999; (99)9999-9999', regex='\\(\\d{2}\\)\\d{4,5}-\\d{4}')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='partneruser',
            name='phone',
            field=models.CharField(default=None, max_length=18, validators=[django.core.validators.RegexValidator(message='Insert a valid phone number. Examples: (99)99999-9999; (99)9999-9999', regex='\\(\\d{2}\\)\\d{4,5}-\\d{4}')], verbose_name='Phone Number'),
        ),
    ]
