# Generated by Django 3.2.3 on 2021-05-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='born_date',
            field=models.DateField(default=None, verbose_name='Born Date'),
        ),
    ]
