# Generated by Django 3.2.3 on 2021-06-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210530_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=100, verbose_name='Address')),
                ('arrival', models.DateField(default=None, verbose_name='Arrival Date')),
                ('departure', models.DateField(default=None, verbose_name='Departure Date')),
            ],
            options={
                'verbose_name': 'Event',
            },
        ),
    ]
