# Generated by Django 3.2.3 on 2021-05-20 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientuser_born_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuser',
            options={'verbose_name': 'Client'},
        ),
    ]
