# Generated by Django 3.2.3 on 2021-06-15 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.partneruser'),
        ),
    ]
