# Generated by Django 3.2.3 on 2021-06-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['departure'], 'verbose_name': 'Event'},
        ),
    ]
