# Generated by Django 3.2.3 on 2021-05-20 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_born_date_clientuser_borndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='phone',
            field=models.CharField(default=None, max_length=18, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Exemplos: (99)99999-9999; (99)9999-9999', regex='\\(\\d{2}\\)\\d{4,5}-\\d{4}')], verbose_name='Phone Number'),
        ),
    ]
