# Generated by Django 3.2.3 on 2021-05-24 01:23

import backend.core.storage
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_rename_born_date_clientuser_borndate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('nationality', models.CharField(default=None, max_length=50, verbose_name='Nationality')),
                ('document', models.FileField(storage=backend.core.storage.OverwriteStorage(location='_private/users/documents'), upload_to='', verbose_name='Document')),
                ('validation', models.BooleanField(default=False, verbose_name='Validation')),
                ('assessmentSum', models.IntegerField(default=0, verbose_name='Assessment Sum')),
                ('assessmentCount', models.IntegerField(default=0, verbose_name='Assessment Count')),
                ('observation', models.CharField(default=None, max_length=5000, verbose_name='Observation')),
                ('phone', models.CharField(default=None, max_length=18, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Exemplos: (99)99999-9999; (99)9999-9999', regex='\\(\\d{2}\\)\\d{4,5}-\\d{4}')], verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Partner',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='phone',
            field=models.CharField(default=None, max_length=18, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Exemplos: (99)99999-9999; (99)9999-9999', regex='\\(\\d{2}\\)\\d{4,5}-\\d{4}')], verbose_name='Phone Number'),
        ),
    ]
