# Generated by Django 3.2.3 on 2021-05-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210523_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneruser',
            name='document',
        ),
    ]
