# Generated by Django 3.2.3 on 2021-06-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemDescription', models.CharField(default=None, max_length=300, verbose_name='Item Description')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('productStatus', models.CharField(default=None, max_length=100, verbose_name='Product Status')),
                ('problemDescription', models.CharField(default=None, max_length=200, verbose_name='problem description')),
                ('itemValue', models.FloatField(default=0, verbose_name='Item Value')),
                ('impost', models.FloatField(default=0, verbose_name='Impost')),
                ('dynamicRate', models.FloatField(default=0, verbose_name='Dynamic Rate')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('address', models.CharField(default=None, max_length=100, verbose_name='Address')),
                ('requestDate', models.DateField(default=None, verbose_name='Request Date')),
                ('orderPlacementDate', models.DateField(default=None, verbose_name='Order Placement Date')),
                ('deliveryDate', models.DateField(default=None, verbose_name='Delivery Date')),
                ('taxation', models.BooleanField(default=False, verbose_name='Taxation')),
                ('clientUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.clientuser')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
