# Generated by Django 3.2.3 on 2021-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['arrival'], 'verbose_name': 'Event'},
        ),
        migrations.AddField(
            model_name='service',
            name='clientFeedback',
            field=models.TextField(default=None, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='service',
            name='problemDescription',
            field=models.CharField(default=None, max_length=200, verbose_name='Problem Description'),
        ),
    ]
