# Generated by Django 3.2.3 on 2021-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210717_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='productStatus',
        ),
        migrations.AddField(
            model_name='service',
            name='produtcStatus',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('order on the way', 'order on the way'), ('Order Delivered', 'Order Delivered'), ('Request under Analysis', 'Request under Analysis'), ('Taxed order', 'Taxed order'), ('address not found', 'address not found'), ('Problems in sending', 'Problems in sending')], max_length=100, null=True, verbose_name='Product Status'),
        ),
    ]
