# Generated by Django 3.2.3 on 2021-07-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210715_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='clientFeedback',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Feedback'),
        ),
    ]
