# Generated by Django 3.2.3 on 2021-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210717_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='problemDescription',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Problem Description'),
        ),
    ]
