# Generated by Django 3.2.3 on 2021-07-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_service_problemdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='produtcStatus',
            new_name='productStatus',
        ),
    ]
