# Generated by Django 3.2.3 on 2021-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_produtcstatus_service_productstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='dynamicRate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='impost',
        ),
        migrations.AddField(
            model_name='service',
            name='dynamicTax',
            field=models.FloatField(default=0, verbose_name='Dynamic Tax'),
        ),
        migrations.AddField(
            model_name='service',
            name='fixedTax',
            field=models.FloatField(default=10, verbose_name='fixed Tax'),
        ),
        migrations.AddField(
            model_name='service',
            name='totalValue',
            field=models.FloatField(default=0, verbose_name='Total Value'),
        ),
    ]
