# This is a basic workflow to help you get started with Actions

name: Build & test django project

# Controls when the workflow will run
on:

  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

  test:
    runs-on: ubuntu-latest
    needs: build
    name: tests
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup python environment
        uses: actions/setup-python@v2
        
      - name: Run tests
        run: python manage.py test backend.core.tests